name: "Auto Release based on version file"
description: "Create a release automatically"

branding:
  color: yellow
  icon: package

inputs:
  version_file:
    description: "File were the version is"
    required: false
    default: "VERSION"

  update_released_versions:
    description: "Update vX and vX.Y versions if a new vX.Y.Z version is released"
    required: false
    default: 'false'

runs:
  using: "docker"
  image: "Dockerfile"
